Feature/payments2.0
sigdotcom/phoenix pull request #31
Opened 2019-03-10 21:10 UTC by kevinschoonover

2019-03-12 18:07 UTC, ClayMav requested changes
Coverage is atrocious, but I don't have much to criticize. I think it's likely mostly fine, but I figured I would comment anything I could think of.

2019-03-12 18:07 UTC, ClayMav commented on src/controllers/Account.ts
> +    if (
Should probably reverse order of these conditions

2019-03-12 18:07 UTC, ClayMav commented on src/controllers/Account.ts
> +    if (
Same as above

2019-03-12 18:07 UTC, ClayMav commented on src/controllers/Account.ts
> +    if (
Swap

2019-03-12 18:07 UTC, ClayMav commented on src/controllers/Account.ts
> +    if (
Swap

2019-03-12 18:07 UTC, ClayMav commented on src/controllers/Product.ts
> +      return Product.delete({ id });
Does this deal with the case that the Product does not exist

2019-03-12 18:07 UTC, ClayMav commented on src/controllers/Product.ts
> +      return Product.delete({ id });
Also a bigger question as to all other cases above

2019-03-12 18:07 UTC, ClayMav commented on src/controllers/Product.ts
> +      return Product.delete({ id });
For instances of find, I cannot find documentation as to the behavior of not existing, nor for delete

2019-03-12 18:07 UTC, ClayMav commented on src/controllers/index.ts
> +export * from "./Account";
I think exporting explicitly instead of * would be better here, since you are just instantly mapping over all exports from this file

2019-03-12 18:07 UTC, ClayMav commented on src/middleware/auth.ts
> +      callbackURL: `http://localhost/auth/google/callback/`,
hardcoded url

2019-03-12 18:07 UTC, ClayMav commented on src/middleware/auth.ts
> +      userProfileURL: "https://www.googleapis.com/oauth2/v3/userinfo"
hardcoded url

2019-03-14 00:00 UTC, kevinschoonover commented on src/controllers/Product.ts
> +      return Product.delete({ id });
It will technically throw an error, but I don't know if that is quite an issue yet as it is highly visible and I am sure there is something in routing-controllers that would handle that. I think this is something to make an issue for but outside the scope of this pr.

2019-03-14 00:00 UTC, kevinschoonover commented on src/middleware/auth.ts
> +      userProfileURL: "https://www.googleapis.com/oauth2/v3/userinfo"
the only way to not hardcode this url is through complicated api calls to google's api.

2019-03-14 00:00 UTC, kevinschoonover commented on src/middleware/auth.ts
> +      callbackURL: `http://localhost/auth/google/callback/`,
Outside the scope of this PR, but I will make an issue to solve this for future iterations

2019-03-20 21:26 UTC, ClayMav approved these changes

2019-03-20 21:37 UTC, merged